### ISSUE TITLE
Collecting data from attendees during the session

### ISSUE THREAD

**Issue by cforgaci** [ClementineCttn/BK-TT-Rbanism#3]
One way to get the survey data would be to read it in directly from `csv` files, as discussed in our first meeting. When the goal is to collect responses through a survey, this approach has a few disadvantages:
- respondents need to fill in the sheets correctly, i.e., without using the separator (e.g. a comma) used by the `csv` file; 
- `csv` files are not 'friendly', that is, the data is shown in plain text, with fields separated by ',' or ';', not in tables;
- files are either named differently, or respondents need to name the files after 
- each respondent creates a separate file, which need to be read in and combined for analysis;
- after filling in the survey, respondents need to send the `csv` files by email.

```r 
# read survey data from csv files
files <- list.files(pattern="^survey-")
survey <- tibble()
for (i in seq_along(files)){
    survey <- rbind(survey, t(read_csv(files[i])[,2]))
}
```

This approach is error-prone and involves too many steps. With Google forms we can easily deploy a survey and to store the data in Google sheets, so instead of `csv` files we could use the `googlesheets4` package to read in the survey data from there. Filling in the survey is user-friendly and the obtained data is nicely returned in tibbles.

```r 
# read survey data from a Google sheet that stores the survey responses
# note that getting data via `googlesheets4` requires a Google account
survey_google <- read_sheet("https://docs.google.com/spreadsheets/d/1_eErh6dy7uMiEewDc4OW_R3sl0qah2-1kYj3JW9H5tA/edit?resourcekey#gid=800252241")

# clean survey data
colnames(survey_google) <- c("timestamp", "name", "year_start_tud", "place", "interest_r", "progr_exp")
survey_google <- survey_google %>%
    mutate(progr_exp = ifelse(progr_exp == "Yes", TRUE, FALSE)) 

# print cleaned survey data
survey_google
survey_google %>% 
    kbl() %>%
    kable_styling(bootstrap_options = c("striped", "hover"))
```

@ClementineCttn, what do you think, should we go for the second option?

**Comment by ClementineCttn** [comment]
Ok for the second option to be filled by participants during the session.
I would keep the dummy-survey in the repo and the code to read them as a bonus for those interested though, to show that there are various options possible

**Comment by cforgaci** [comment]
For future runs of the demonstration, add a country field in the form to ensure that geocoding is more accurate.

**Comment by cforgaci** [comment]
I am closing this issue. We might pick it up again as part of our [GDCU workshop](https://github.com/carpentries-incubator/r-geospatial-urban).
