### ISSUE TITLE
Graphs in demo.Rmd

### ISSUE THREAD

**Issue by cforgaci** [ClementineCttn/BK-TT-Rbanism#4]
@ClementineCttn, for the Making Graphs section of `demo.Rmd`, we can:
1. plot the data from the survey as a basic example
2. plot a bigger dataset, maybe [gapminder](https://cran.r-project.org/web/packages/gapminder/README.html), maybe one of your datasets to illustrate the data visualisation capabilities of R

For both, it would be nice to show the data frame, the code and the plot.

**Comment by ClementineCttn** [comment]
Ok, I'll do this part next week
