### ISSUE TITLE
Pb au authentification with googlesurvey

### ISSUE THREAD

**Issue by ClementineCttn** [ClementineCttn/BK-TT-Rbanism#5]
survey_google <- read_sheet("https://docs.google.com/spreadsheets/d/1_eErh6dy7uMiEewDc4OW_R3sl0qah2-1kYj3JW9H5tA/edit?resourcekey#gid=800252241")

I (and the participant) need authorization to access the survey... Is it possible to make it open?

**Comment by cforgaci** [comment]
I made it accessible to anyone with a link. Does it work now?

**Comment by ClementineCttn** [comment]
Yes it does! thank you

**Comment by cforgaci** [comment]
I added `googlesheets4::gs4_deauth()` to the script and made the google sheet entirely public for editing. @ClementineCttn, can you please check if reading the data from google works for you now?

**Comment by ClementineCttn** [comment]
@cforgaci Yes, it works! Thanks.
